#!/usr/bin/env php
<?php

use Mocchi\Console\Cli;
use Mocchi\Console\Input;
use App\Container;
use Doctrine\Common\Annotations\AnnotationRegistry;

define('MOCCHI_START', microtime(true));
define('APP_PATH', realpath(implode(DIRECTORY_SEPARATOR, [__DIR__])));

$loader = require __DIR__.'/vendor/autoload.php';

AnnotationRegistry::registerLoader([$loader, 'loadClass']);

$dotenv = Dotenv\Dotenv::createImmutable(APP_PATH);
$dotenv->load();

set_time_limit(0);

$container = new Container();

$input = new Input();

$input->setArgs($argv);

$cli = new Cli($input);

$cli->terminate();
