framework:
    secret: S0ME_SECRET
    profiler: { only_exceptions: false }

    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
