routes:
  - path: /
    name: index
    method: index
    controller: Login

  - path: /logout
    name: logout
    method: logout
    controller: Login

  - path: /login
    name: login
    method: login
    http_method: GET
    controller: Login
    middleware:
      - Http

  - path: /dashboard
    name: dashboard_index
    method: index
    controller: Dashboard
    middleware:
      - JwtValidation

  - path: /jwt/{id}
    name: jwt_test
    method: jwt
    controller: Login
    middleware:
      - Auth

  - path: /error/404
    name: not_found
    method: e404
    controller: static
